version: '2'
services:
    frontend:
      build: ./client/.
      image: image-demo-frontend:latest-dev
      environment:
        - IMAGE_API=http://localhost:8081
      volumes:
        - ./client/src:/app/src
      command: npm run start:dev
      ports:
        - 8080:8080
    backend:
      build: ./server/.
      image: image-demo-backend:latest-dev
      environment:
        - REDISURI=redis://redis:6379/0
      volumes:
        - ./server:/app
      command: npm run start:dev
      ports:
        - 8081:8080
    redis:
      image: redis:3
      ports:
        - 6379:6379
      volumes:
        - ./tmp/redis:/data